issue-11
BlokhinaElizaveta/liquid-log pull request #10
Opened 2018-12-12 18:08 UTC by BlokhinaElizaveta

@d0k1 @ykalemi @etitov

2018-12-13 08:03 UTC, ykalemi requested changes
небольшие замечания

полноценно можно будет проверить в следующей задаче - насколько легко будет добавить новый парсер

2018-12-13 08:03 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +import ru.naumen.sd40.log.parser.ParserServices.ParserService;
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces

2018-12-13 08:03 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/HistoryController.java
> +            this.dataTypes.put(typeName.split("_")[0], dataTypes.get(typeName));
> typeName.split("_")[0]

это накладывает ограничения на именование DataType. Ограничения не явные, и их легко не соблюсти.

2018-12-13 08:03 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/InfluxDBWriter.java
> +        if (dataSet instanceof SdngDataSet && trace) {
сейчас это можно пропустить. Но это не очень хороший код. Мы вдруг начинаем знать про наличие конкретной реализации DataSet. Логичнее отдать это внутрь чего-то, что касается SdNg.
(можно и внутрь DataSet, т.е. добавить какой-то интерфейс, что данные должны логироваться - но именно DataSet тоже не самое удачное для этого место)

2018-12-13 19:15 UTC, BlokhinaElizaveta commented
@ykalemi 
переименовала папки и теперь в интерфейсе DataType есть метод, который должен возвращать имя типа

2018-12-14 04:41 UTC, ykalemi approved these changes

2018-12-14 05:02 UTC, merged