issue-3
BlokhinaElizaveta/liquid-log pull request #3
Opened 2018-10-15 19:34 UTC by BlokhinaElizaveta

@d0k1 @ykalemi @etitov

2018-10-16 06:32 UTC, ykalemi requested changes

2018-10-16 06:32 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/TopTimeParser.java
> +        return 0L;
Я подозреваю, что TopParser сейчас работает некорректно. Дело в том, что этот парсер значительно отличается от остальных - лог, который он парсит, многострочный. Т.е. здесь несколько строк относятся к одному моменту времени. Т.е. при рефакторинге изменилось поведение.

Пример лога скину в канал.

2018-10-17 14:09 UTC, BlokhinaElizaveta commented on src/main/java/ru/naumen/sd40/log/parser/TopTimeParser.java
> +        return 0L;
поправила topParser

@d0k1 @ykalemi @etitov

2018-10-18 13:44 UTC, ykalemi approved these changes
Теперь - ок.
Есть один вопрос по наименованию метода, можно сделать другим коммитом без pull request.

Ещё есть какая-то проблема с перезаписыванием файлов (на ревью это так выглядит), но не знаю что подсказать. Это скорее всего какая-то особенность вашей IDE или операционной системы

2018-10-18 13:44 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +    public static long prepareTime (long time) {
очень не говорящее название метода

2018-10-18 13:44 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +package ru.naumen.sd40.log.parser;
Не очень понятно, что случилось с этим файлом, почему он целиком попал в коммит, хотя изменений должно быть мало

2018-10-18 13:44 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/NumberUtils.java
> +public class NumberUtils
Здесь тоже как будто весь файл перезаписан, хотя это не так.

2018-10-18 13:50 UTC, BlokhinaElizaveta commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +package ru.naumen.sd40.log.parser;
Да странно, в первом коммите (issue-3) было нормально всё

2018-10-18 17:10 UTC, merged