issue-4
BlokhinaElizaveta/liquid-log pull request #4
Opened 2018-10-23 17:35 UTC by BlokhinaElizaveta

@d0k1 @ykalemi @etitov

2018-10-24 13:50 UTC, ykalemi requested changes

2018-10-24 13:50 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/DataSetService.java
> +    private String finalInfluxDb;
Часть названия `final` уже не имеет никакого смысла в этом контексте. Лучше переименовать

2018-10-24 13:50 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/DataSetService.java
> +            write();
Метод write является частью публичного интерфейса. Но используется он единственный раз - внутри реализации. Это точно интерфейс?

2018-10-24 13:50 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/OneLineParser.java
> +        dataParser.parseLine(line, dataSetService.get(key));
Напишите, пожалуйста, тест, повторяющий логику парсинга нескольких строк. Т.е. вызывать два раза dataSetService.get для разных ключей и проверить сколько сохранилось ключей в базу

2018-10-25 16:36 UTC, BlokhinaElizaveta commented
@ykalemi 
Поправила, вынесла метод `write` в интерфейс `DBWriter` и проверила в тестах количество вызовов этого метода (сколько сохранилось ключей в базу)

2018-10-25 16:49 UTC, ykalemi approved these changes

2018-10-25 17:04 UTC, merged