issue-6
BlokhinaElizaveta/liquid-log pull request #6
Opened 2018-11-07 16:13 UTC by BlokhinaElizaveta

@d0k1 @ykalemi @etitov

2018-11-13 18:18 UTC, BlokhinaElizaveta commented
\+ седьмое задание. Сейчас парсеры принимают DataSet в метод `parseLine(String line, DataSet data)` и оттуда достают нужный класс данных.

2018-11-14 07:02 UTC, d0k1 requested changes

2018-11-14 07:02 UTC, d0k1 commented on src/main/java/ru/naumen/sd40/log/parser/ErrorData.java
> +    long warnCount;
private?

2018-11-14 07:02 UTC, d0k1 commented on src/main/java/ru/naumen/sd40/log/parser/GCDataParser.java
> +public class GCDataParser implements DataParser
Spring bean?

2018-11-14 07:03 UTC, d0k1 commented
Если я правильно понял PullRequest по двум заданиям сразу.
но я не увидел Spring Bean'ов (задачание 7)
и есть мелкие замечания по заданию 6

2018-11-14 13:30 UTC, BlokhinaElizaveta commented
@d0k1 
Добавила `private` у полей в классах с данными.
Сделала парсеры бинами, в `LogParser` достаю их из beanFactory.

2018-11-15 13:41 UTC, d0k1 requested changes

2018-11-15 13:41 UTC, d0k1 commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private BeanFactory beanFactory;
BeanFactory - конечно ок.
но есть ли причины просто не сделать DependecyInjection в поля класса?

2018-11-15 17:32 UTC, BlokhinaElizaveta commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private BeanFactory beanFactory;
Сделала в поля класса `LogParser`.

2018-11-15 17:33 UTC, BlokhinaElizaveta commented
@d0k1 поправила)

2018-11-15 17:43 UTC, d0k1 approved these changes

2018-11-15 17:46 UTC, merged